# networks:
#   painelsolidariors:
#     external:
#       name: painelsolidariors

services:
  web:
    container_name: web
    build:
      dockerfile: .docker/Dockerfile.web
      context: .
    restart: unless-stopped
    ports:
      - 3000:3000

  api:
    container_name: api
    build:
      dockerfile: .docker/Dockerfile.api
      context: .
    ports:
      - 4000:4000
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      NODE_ENV: "${NODE_ENV}"
