# Builder
FROM node:20-alpine as builder

# Define build arguments for environment variables
ARG NODE_ENV
ARG VITE_API_URL
ARG VITE_FIREBASE_PUBLIC_PROJECT_ID
ARG VITE_FIREBASE_PUBLIC_API_KEY
ARG VITE_FIREBASE_PUBLIC_AUTH_DOMAIN
ARG VITE_FIREBASE_PUBLIC_STORAGE_BUCKET
ARG VITE_FIREBASE_PUBLIC_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_PUBLIC_APP_ID
ARG VITE_FIREBASE_PUBLIC_MEASUREMENT_ID

USER node
WORKDIR /home/node

COPY --chown=node:node ./*.json ./
COPY --chown=node:node ./apps/web ./apps/web
COPY --chown=node:node ./packages ./packages

WORKDIR /home/node/apps/web

RUN npm install
RUN npm run build

EXPOSE 3000
EXPOSE 80

CMD [ "npm", "run", "preview" ]