# Builder
FROM node:20-alpine as builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY --chown=node:node ./*.json ./
COPY --chown=node:node ./apps/web ./apps/web
COPY --chown=node:node ./packages ./packages

WORKDIR /home/node/apps/web

RUN npm install
RUN npm run build

EXPOSE 3000
EXPOSE 80

CMD [ "npm", "run", "preview" ]