export const CONSTANTS = {
  DATA_SOURCE: 'DATA_SOURCE',
  REPOSITORY: {
    USER: 'USER_REPOSITORY',
    PERSON: 'PERSON_REPOSITORY',
    ADDRESS: 'ADDRESS_REPOSITORY',
    SHELTERS: 'SHELTER_REPOSITORY',
    VOLUNTEER_CATEGORY: 'VOLUNTEER_CATEGORY_REPOSITORY',
    NEED: 'NEED_REPOSITORY',
  },
} as const;
