export const CONSTANTS = {
  DATA_SOURCE: 'DATA_SOURCE',
  REPOSITORY: {
    USER: 'USER_REPOSITORY',
    PERSON: 'PERSON_REPOSITORY',
    PERSON_SHIFT: 'PERSON_SHIFT_REPOSITORY',
    PERSON_ACTIVITY: 'PERSON_ACTIVITY_REPOSITORY',
    PERSON_EMPLOYMENT: 'PERSON_EMPLOYMENT_REPOSITORY',
    VOLUNTEER_CATEGORY: 'VOLUNTEER_CATEGORY_REPOSITORY',
    ADDRESS: 'ADDRESS_REPOSITORY',
    SHELTER: 'SHELTER_REPOSITORY',
    NEED: 'NEED_REPOSITORY',
  },
} as const;
