networks:
  painelsolidariors:
    external:
      name: painelsolidariors

services:
  backend:
    build: .
    ports:
      - 3000:3000
    networks:
      - painelsolidariors
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      NODE_ENV: "${NODE_ENV}"
