name: CI

on:
  push:
    branches:
      - production
      - main
  pull_request:
      branches: '**'

env:
  NODE_VERSION: 20.13

jobs:
  code-check:
    runs-on: ubuntu-latest
    name: ${{ matrix.check == 'ts' && 'TypeScript' || 'Code Lint' }}

    strategy:
      fail-fast: false
      matrix:
        check: ['ts', 'lint']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-modules: true
          install: true

      - name: Code Lint
        if: matrix.check == 'lint'
        run: |
          npm run lint

      - name: Code TypeCheck
        if: matrix.check == 'ts'
        run: |
          npm run typecheck

  test-api:
    name: "API Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-modules: true
          install: true

      - name: Run tests
        run: |
          cd apps/api
          npm test

  test-web:
    name: "Web Tests"
    runs-on: ubuntu-latest
    # runs-on: macos-latest-large

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
        # browser: [chrome, firefox, edge, webkit] #webkit is only available on macOS and emulates Safari

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-modules: true
          install: true

      - name: Start test server
        run: |
          cd apps/web
          docker-compose up -d web

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          project: ./apps/web
          browser: ${{ matrix.browser }}
          group: ${{ runner.os }}/${{ matrix.browser }}
          record: true
          parallel: true
          cache-key: node-${{ matrix.browser }}-on-${{ runner.os }}
        env:
          CYPRESS_RECORD_KEY: faf1cd67-9203-460d-a8bb-b1967f65e337
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-containers:
    name: "Build container"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ['web', 'api']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker Compose Build
        run: |
          docker compose build ${{ matrix.container }}

      - name: Publish Docker image (PR)
        if: github.event_name == 'pull_request'
        run: |
          GH_IMAGE_NAME="ghcr.io/painel-solidario-rs/painel-solidario-${{ matrix.container }}:pr-${{ github.event.number }}"

          docker tag painel-solidario-rs-${{ matrix.container }} $GH_IMAGE_NAME

          docker push $GH_IMAGE_NAME

      - name: Publish Docker image (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          GH_IMAGE_NAME="ghcr.io/painel-solidario-rs/painel-solidario-${{ matrix.container }}:develop"

          docker tag painel-solidario-rs-${{ matrix.container }} $GH_IMAGE_NAME

          docker push $GH_IMAGE_NAME

  deploy:
    name: "Deploy app"
    runs-on: [self-hosted, production, painel-solidario-rs]
    needs: [test-api, test-web, build-containers]
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cschleiden/replace-tokens@v1
        with:
          files: 'docker-compose.yml'
          tokenPrefix: "${"
          tokenSuffix: "}"
        env:
          APP_DB_PASSWORD:  ${{ vars.APP_DB_PASSWORD }}
          APP_DB_USERNAME:  ${{ vars.APP_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}
          JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION }}
          CRYPTO_SECRET: ${{ vars.CRYPTO_SECRET }}
          FIREBASE_ADMIN_CREDENTIALS_JWT: ${{ vars.FIREBASE_ADMIN_CREDENTIALS_JWT }}
          VITE_API_URL : ${{ vars.VITE_API_URL }}
          VITE_FIREBASE_PUBLIC_API_KEY : ${{ vars.VITE_FIREBASE_PUBLIC_API_KEY }}
          VITE_FIREBASE_PUBLIC_AUTH_DOMAIN : ${{ vars.VITE_FIREBASE_PUBLIC_AUTH_DOMAIN }}
          VITE_FIREBASE_PUBLIC_PROJECT_ID : ${{ vars.VITE_FIREBASE_PUBLIC_PROJECT_ID }}

      - name: Starts application
        run: |
          docker compose up --build -d